import localFont from "next/font/local";
import "./globals.css";
import "./layout.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <nav className=" flex flex-col md:flex-row sticky z-50 justify-evenly md:justify-items-end">
          <Link href={'/'}>Home</Link>
          <Link href={'/profile'}>Profile</Link>
          <Link href={'/share'}>Share</Link>
        </nav>
        {children}
        <footer className="mt-auto text-center py-4">
        <p className="text-gray-500">&copy; 2023 Whisper. All rights reserved.</p>
      </footer>
      </body>
    </html>
  );
}
